language: python
dist: trusty

python:
  - "3.6"

git:
  depth: false

install: travis_retry pip install -r requirements.txt

before_script:
  - flake8 src
  - python setup.py install -f

script:
  - sphinx-build -M html docs build

deploy:
  - provider: pages
    skip-cleanup: true
    local-dir: build/html
    github-token: "${GITHUB_REPO_TOKEN}"
    keep-history: true
    on:
      branch: master

  - provider: pypi
    skip_cleanup: true
    user: "${PYPI_USER_NAME}"
    password: "${PYPI_PASSWORD}"
    distributions: sdist
    on:
      branch: master

notifications:
  email: true
